name: notysafe
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_secure_storage: ^9.2.4
  local_auth: ^2.3.0
  flutter_staggered_grid_view: ^0.7.0
  package_info_plus: ^8.3.0
  url_launcher: ^6.3.1
  sqflite: ^2.4.2
  path: ^1.9.1
  flutter_quill: ^11.1.0
  flutter_quill_extensions: ^11.0.0
  flutter_localizations:
    sdk: flutter
  encrypt: ^5.0.3
  crypto: ^3.0.6
  easy_localization: ^3.0.7+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.3"

flutter:
  uses-material-design: true
  assets:
    - assets/translations/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21